In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [12]:
# Get Dimension
a.ndim
b.ndim

2

In [13]:
# Get Shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [4]:
# Get Type
a.dtype

dtype('int16')

In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Size
a.itemsize
b.itemsize

8

In [12]:
# Get Total Size
a.nbytes
b.nbytes

48